### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by mayowadavid** [abhiint16/NewsAppUpdate#1]
Hello, @abhiint16 am a graphics designer. I will like to know if you want me to create a logo for your project. I will be creating it for free.

**Comment by mayowadavid** [comment]
Hi, @abhiint16 are you there?

**Comment by mayowadavid** [comment]
Hello @abhiint16

**Comment by abhiint16** [comment]
Hey ,

Can you brief me more about it. How do you work?

Thanks
Regards
Abhishek Kumar

**Comment by mayowadavid** [comment]
@abhiint16, i always create the logo based on request for free. I make a multiple sketch of the app logo then select the one that fit the application. After the whole process i will make a presentation for review. If you like it, i will proceed to make a pull request, while i also submit editable file for further use.

**Comment by abhiint16** [comment]
Hey,

This sounds awesome. But I wanna know one thing here, why do you make
things for free? What purpose does it serve for you ?

Thanks
Regards
Abhishek Kumar

**Comment by mayowadavid** [comment]
@abhiint16 It serves as means to increase my portfolio. Though some project owners do compensate effort, but that is based on choice.

**Comment by abhiint16** [comment]
Hey David,

I really appreciate your hunger for work. I would love to collaborate with
you just not for this project but for my future projects too.

How can we start with the process?

Thank
Regards
Abhishek Kumar

**Comment by mayowadavid** [comment]
@abhiint16  i will go and get something done, why i come back for you to review it.

**Comment by abhiint16** [comment]
Sure David.

**Comment by mayowadavid** [comment]
Hello, @abhiint16 Sorry for delay. I have a problem with my PC i just got it fixed. After several sketch this is what i came up with.
![update-app-present](https://user-images.githubusercontent.com/34623610/45364110-35c9a580-b5d1-11e8-8378-487e1ce2a4db.png)
If you like it, i will proceed to put it into different sizes. You can also make suggestion on what you will like to be removed or added.

**Comment by abhiint16** [comment]
Hey bro,

For me nothing matters more than the effort that you have put in. I really
liked it and would certainly integrate it in my app.

Can you also come up with a banner image that looks good with the logo of
the app. As having the banner image as it is and changing the logo itself
would not work well.

I actually like that green one. You can also add me on Whatsapp with the no
+91-9958134029. I really like to be connected with people like you who
don't hesitate making efforts.

Thanks
Regards
Abhishek Kumar

**Comment by mayowadavid** [comment]
@abhiint16 Am glad you like it, i will create other size variation for the green color and also banner as you requested. I will also submit a link for editable version of the application. I will chat with you on whatsapp, as i will save your your number now.

**Comment by mayowadavid** [comment]
Hi, @abhiint16 this is the link to editable file [here](https://drive.google.com/folderview?id=1-CfMhIymbCs8ipSurQYDZMvr7p-_qAW2)
